scrape_configs:
  - job_name: 'authorization_monitoring'
    scrape_interval: 15s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8187', 'authorization:8187']

# localhost:8187 для запуска из IDE
# authorization:8187 для запуска из Docker